from setuptools import setup, find_packages

setup(
    name="transcribe_meeting",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "faster-whisper",
        "pyannote.audio",
        "ffmpeg-python",
        "torch",
        "numpy",
        "pandas",
        "scikit-learn",
        "scipy",
        "tqdm",
        "requests",
        "pytz",
        "PyYAML",
        "coloredlogs",
        "colorlog",
        "joblib",
        "Jinja2",
        "markdown-it-py",
        "matplotlib",
        "networkx",
        "optuna",
        "SQLAlchemy",
        "tabulate",
        "tensorboardX",
        "torchmetrics",
        "torchvision",
        "typer",
        "typing_extensions",
        "yarl",
    ],
    entry_points={
        "console_scripts": [
            "transcribe_meeting=transcribe_meeting.transcribe_meeting:main",
        ],
    },
    author="Codeacula",
    author_email="codeacula@example.com",
    description="A tool for transcribing and diarizing video meetings.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/codeacula/codeaculas-personal-bots",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
